### ISSUE TITLE
Node install fail silently

### ISSUE THREAD

**Issue by jeanmonod** [liip/drifter#160]
If the nodejs install generate an error, it fail without any notice (white line)

    TASK [composer : add composer binary dir to path] ******************************
    changed: [default]

    TASK [nodejs : fail] ***********************************************************

    TASK [nodejs : fail] ***********************************************************

    TASK [nodejs : Make sure APT supports HTTPS sources] ***************************

**Reproduction Steps:**

1. Write a broken package.json script
2. vagrant uo
3. See that there was no error message

**Expected behavior:**

Provisionning should fail

**Drifter version:** 1.1.1
**Vagrant version:** 1.8.5

**Comment by jeanmonod** [comment]
Ok, it seems that this is the normal behavior: http://docs.ansible.com/ansible/fail_module.html#synopsis

It's just that the output is misleading...

Can we cleanup that output?

**Comment by sephii** [comment]
The node role doesn't run `npm install` or anything that would use `package.json`. Since the `virtualenv` role for Python and the `ruby` role for Ruby both try to install requirements files I guess it would make sense to have the `node` role install the `package.json`.

**Comment by sephii** [comment]
Closing this in favour of #161.
