### ISSUE TITLE
Make node role install package.json

### ISSUE THREAD

**Issue by sephii** [liip/drifter#161]
Currently the `node` role only installs `node` but doesn't do anything if there's a `package.json` file, which isn't coherent with the `virtualenv` and `ruby` roles. We should make the role run `npm install` when provisioning if there's a `package.json` file.

**Comment by LeBenLeBen** [comment]
It’s done in the Gulp role today, which depends on Node. We could do it in Node tasks but we’ll have to redo it for Gulp as the `package.json` is created after Node is installed. Would that be ok for you?

**Comment by sephii** [comment]
Sure, the second `npm install` should be quick anyway.

**Comment by LeBenLeBen** [comment]
Another solution would be to have a `package.json` template in the Node.js role which could be overridden by Gulp. `npm install` could be then run by the Node role but after the `package.json` is created.

My only interrogation here is: should we create a basic `package.json` with just the mandatory fields by default or just no file at all? Running `npm install` without package.json is allowed. I don’t see any use case where you would install Node without any subscequent packge.json but I also don’t like creating configuration file for no reason.

WDYT?

**Comment by LeBenLeBen** [comment]
⚠️  Command should be different if user decided to use Yarn instead of NPM.

**Comment by sephii** [comment]
@LeBenLeBen since we now use NPM 5 should we deprecate the usage of Yarn?

**Comment by LeBenLeBen** [comment]
@sephii No, I don’t think so, it’s still under active development and some developers prefer yarn to npm.
