### ISSUE TITLE
New files are not watched by Gulp

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/drifter#165]
At the moment when you create new Sass partials or such, they are not watched by the watch task. It force you to kill gulp and restart it. If we move to [gulp-watch](https://www.npmjs.com/package/gulp-watch) those could be handled as well.

**Comment by LeBenLeBen** [comment]
ℹ️  Gulp-watch seems to have issues to see file changes inside Vagrant boxes 😭

**Comment by sephii** [comment]
@LeBenLeBen is there anything we can do on the drifter side to help with this? I tested it with LXC and it works fine.

**Comment by LeBenLeBen** [comment]
I didn’t find a good and easy solution to this sadly.
