### ISSUE TITLE
mysql-common can't be authenticated

### ISSUE THREAD

**Issue by jdavidlopez** [liip/drifter#197]
Apparently mySQL certificate expired on Feb, 2017 and therefore there's an error with mysql on provisioning.

This should be solved just adding the correct key for apt https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x8C718D3B5072E1F5

**Comment by chregu** [comment]
This should be fixed since quite some time on our side. Which version or "commit hash" are you using?

**Comment by jdavidlopez** [comment]
As far as I know (not familiar with submodules in git) we're just adding it in .gitmodules

[submodule "drifter"]
        path = virtualization/drifter
        url = https://github.com/liip/drifter.git

So (as far as I know again) no version specified.

**Comment by jdavidlopez** [comment]
Ok, I discovered how. My fault. Sorry :-)
