### ISSUE TITLE
npm install is not executed

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/drifter#222]
The handler to run "npm install" doesn’t have any effect because Ansible thinks there are no packages missing and therefor skip the command. This seems to be caused by a change in the JSON `npm list --json` produce which doesn’t allow Ansible to detect missing npm packages.

Maybe an update of Ansible would fix the issue?

**Reproduction Steps:**

1. Enable a role using Node (Gulp or Webpack)
2. Provision the box

**Expected behavior:**

A `node_modules` folder is created and packages listed in the `package-json` are installed

**Observed behavior:**

`node_modules` folder is not created an no packages are installed.

**Drifter version:** 1.7.0
**Vagrant version:** 2.0.4
**OS and version:** macOS 10.13.1
**Ansible version:** 2.1.1.0

* Problem started happening recently, didn't happen in an older version of Drifter: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens to my colleagues aswell or only me: Yes

**Comment by LeBenLeBen** [comment]
Seems to have been fixed in Ansible so an update would probably resolve this, see https://github.com/ansible/ansible/pull/26582

**Comment by chregu** [comment]
Fixed in #236 if you define a higher ansible version (like 2.7.0) in parameters.yml 
Please reopen, if you think this should be fixed differently
