### ISSUE TITLE
Supervisor with anonscm.debian is closed

### ISSUE THREAD

**Issue by RSickenberg** [liip/drifter#224]
:arrow_up: Ensure you have put a meaningful title in the box up there. :arrow_up:

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
- vagrant provision with supervisor
2. [Second Step]
- Wait
3. [Other Steps...]
- Enjoy
**Expected behavior:**
- Use the git repo from git://ansonscm.debian/collab-maint/supervisor.git
[Describe expected behavior here]

**Observed behavior:**
`
TASK [supervisor : get debian package files] ***********************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote git://anonscm.debian.org/collab-maint/supervisor.git -h refs/heads/HEAD", "failed": true, "msg": "fatal: unable to connect to anonscm.debian.org:\nanonscm.debian.org[0: 194.177.211.202]: errno=Connection refused\nanonscm.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable", "rc": 128, "stderr": "fatal: unable to connect to anonscm.debian.org:\nanonscm.debian.org[0: 194.177.211.202]: errno=Connection refused\nanonscm.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable\n\n", "stdout": "", "stdout_lines": []}
`
[Describe observed behavior here]

**Drifter version:** 1.2
**Vagrant version:** 2.1.1
**OS and version:** MacOS 10.13.5

**Configuration files:**

Zebra config

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Drifter: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens to my colleagues aswell or only me: 🤷‍♂️

**Comment by OdyX** [comment]
This is an issue caused by the deprecation of Debian's Alioth (anonscm.debian.org).
