### ISSUE TITLE
Ansible emit deprecation warnings

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/drifter#237]
Since at least Ansible 2.7, some roles emits deprecation warnings. Here are the type I found so far:

> [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `pkg: {{ item }}`, please use `pkg: [u'locales', u'procps', u
'command-not-found', u'bash-completion', u'zsh', u'bzip2', u'unzip', u'vim', u
'ack-grep', u'highlight', u'libxml2-utils', u'build-essential', u'wget', u
'openssh-server', u'sudo', u'imagemagick', u'iputils-ping', u'ncurses-term', u
'python-pycurl']` and remove the loop. This feature will be removed in version 
2.11.

> [DEPRECATION WARNING]: Invoking "pip" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: {{ item }}`, please use `name: [u'pip==9.0.1', 
u'setuptools==28.8.0', u'tox==2.6.0']` and remove the loop. This feature will 
be removed in version 2.11.

> [DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using 
`result|success` use `result is success`. This feature will be removed in 
version 2.9.

> [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ ansible_python_version |
version_compare('2.7.9', '<') }}

**Comment by chregu** [comment]
I started in #238, but didn't come far ;)

**Comment by sephii** [comment]
Should be fixed. :)
