### ISSUE TITLE
`webpack_package_json_path` parameter is not used at all

### ISSUE THREAD

**Issue by krtek4** [liip/drifter#254]
When including the webpack role, according to the documentation, you can set `webpack_package_json_path` to determine where the `package.json` file should be created.

This value is however never passed to the `nodejs` role and isn't used anywhere ( https://github.com/liip/drifter/search?q=webpack_package_json_path&unscoped_q=webpack_package_json_path )

**Comment by LeBenLeBen** [comment]
This parameter, as well as `gulp_package_json_path` have been replaced by `nodejs_package_json_path` since creating the package.json is handled by the nodejs role. I therefor removed any mention of those two parameters.

Thanks for reporting!
