### ISSUE TITLE
Update Debian apt sources

### ISSUE THREAD

**Issue by ghn** [liip/drifter#261]
**Reproduction Steps:**

1. vagrant provision

**Expected behavior:**

success

**Observed behavior:**

`apt-get update` command fails

```
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Get:4 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
 404  Not Found
```

**Drifter version:** master
**Vagrant version:** any
**OS and version:** any

**Comment by ghn** [comment]
ok found a solution for my old project: Just update the `parameters.yml` as defined here https://github.com/liip/drifter/blob/master/parameters.yml.dist

**Comment by sephii** [comment]
@ghn you mean you switched to a different debian release? Or you managed to stay in jessie and fix the issue?

**Comment by ghn** [comment]
I moved to `drifter/stretch64-base`

**Comment by LeBenLeBen** [comment]
Ok so let's keep this open as some people might not be able to upgrade.

**Comment by krtek4** [comment]
From @OdyX  on Slack :

> https://lists.debian.org/debian-lts/2019/04/msg00011.html

Debian is currently discussing adding the repo again to the archive, so the issue might sort itself out.

**Comment by OdyX** [comment]
From: https://lists.debian.org/debian-lts/2019/04/msg00097.html
> JFTR, jessie-updates is back.

Indeed:
https://deb.debian.org/debian/dists/jessie-updates/Release doesn't 404 anymore
