### ISSUE TITLE
Find a new name for this project

### ISSUE THREAD

**Issue by jeanmonod** [liip/drifter#46]
Feel free to write down proposal as comments ;)

**Comment by ChristianRiesen** [comment]
VMinator 6000, better than the 3000 model but not as expensive ad the 9000 model. Sorry got nothing pithy.

**Comment by sephii** [comment]
I quite like the name Drifter @krtek4 proposed.

**Comment by krtek4** [comment]
+1 for *Drifter* :P

**Comment by ChristianRiesen** [comment]
For simple curiosity, what's the idea behind using the name Drifter? Not obvious to me here at least :)

**Comment by chregu** [comment]
@ChristianRiesen:  https://www.urbandictionary.com/define.php?term=Vagrant ;)
