### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sephii** [liip/drifter#48]
At the moment everything is documented in the README and it's a pain to browse. Also the documentation for certain roles is outdated (some of it being mea culpa). We should have a complete, up-to-date documentation (hosted on readthedocs?).

## To document
- [ ] Review current documentation and ensure it is up to date 
- [ ] Apache parameters
- [ ] Python Flask
- [ ] Java / JDK / Maven / SOLR (@fabricehong)
- [x] Node
- [x] Compass (@lebenleben)
- [x] Gulp (@lebenleben) see #84
- [ ] Redis
- [ ] RMT (@jeanmonod)

**Comment by krtek4** [comment]
Maybe creating a github pages for the project with a documentation is a solution ?
We will need some kind of landing page at some time anyway.

**Comment by krtek4** [comment]
I decided to go with ReadTheDocs : http://liip-drifter.readthedocs.org/

I already moved the various documentation from the README.md to separated markdown files in the `docs` directory. Hopefully I made no mistake and RTD will soon build it.

I added placeholders for all roles in the project, but a lot of documentation is either missing or outdated :( All help greatly appreciated !

**Comment by krtek4** [comment]
> just a small improvement suggestion. The documentation doesn't include a link to the GitHub repo:
> https://readthedocs.org//search/?q=github&check_keywords=yes&area=default&project=liip-drifter&version=latest&type=file
> Reason is: I usually like to bookmark and share links to the documentation

**Comment by LeBenLeBen** [comment]
I’ve added a list of topics missing to the first post to track progress.

**Comment by krtek4** [comment]
Maybe we should start to define a common template to document the roles, I am not sure the current one is great.

Also, most of the roles documentation is probably outdated and should be checked, I'll add that to the list.

**Comment by krtek4** [comment]
Documentation was migrated to RTD and is roughly up to date. Some roles aren't documented but this can be fixed later.
