### ISSUE TITLE
ansible detection doesn't work on lxc with "vagrant provision"

### ISSUE THREAD

**Issue by chregu** [liip/drifter#56]
Looks like when I do "vagrant provision" on lxc, it doesn't go through that detection if it should use ansible or ansible_local and fails like in https://github.com/fgrehm/vagrant-lxc/issues/398

Not sure how to solve this, if someone has an idea, go ahead, or i'll look into it soonish

**Comment by chregu** [comment]
seems to be something different... investigating...

**Comment by krtek4** [comment]
Merged !

Since I mainly use the `VAGRANT_DEFAULT_PROVIDER` env variable, I didn't test the CLI arguments detection enough. Sorry for that and thanks for the patch :)
