### ISSUE TITLE
Git config shared between host and box

### ISSUE THREAD

**Issue by jeanmonod** [liip/drifter#62]
As a developper, I commonly work inside the box for many development tasks that doesn't only rely on the file system. So very often, as I'm already into the box, when I use git too, but unfortunately I don't have my git config there. So I have to go outside to be able to use my preferred aliases and my identify.
Can we find a way to shared all or a part of the git config with the box?
One solution I see is to copy the user `.gitconfig` into the box user home. But maybe we can find something more elegant and propose that as a nice drifter feature?

**Comment by krtek4** [comment]
We already set e-mail and username based on the host : https://github.com/liip/drifter/blob/master/provisioning/roles/base/tasks/main.yml#L74

Copying the file might be an idea, but in the long run they could differ so it would probably lead to confusion (same with the username / email BTW).

From the documentation :

> FILES
       If not set explicitly with --file, there are four files where git config will search for configuration options:

       $(prefix)/etc/gitconfig
           System-wide configuration file.

       $XDG_CONFIG_HOME/git/config
           Second user-specific configuration file. If $XDG_CONFIG_HOME is not set or empty, $HOME/.config/git/config will be used. Any single-valued variable set in this file will be overwritten by whatever is in ~/.gitconfig. It is
           a good idea not to create this file if you sometimes use older versions of Git, as support for this file was added fairly recently.

       ~/.gitconfig
           User-specific configuration file. Also called "global" configuration file.

       $GIT_DIR/config
           Repository specific configuration file.

**Comment by krtek4** [comment]
Do not forget the "issue" when using `ansible_local` : #87

**Comment by krtek4** [comment]
This is not an opt-in in the latest yet to be released version.
