### ISSUE TITLE
Document dependency on redir

### ISSUE THREAD

**Issue by etoulas** [liip/drifter#66]
When running `vagrant up --provider lxc` on Ubuntu 14.04, vagrant complains that `redir` is missing.
> `redir` is not installed or is not accessible on the PATH.

If someone could confirm that this is indeed need and went unnoticed, then I'll be happy to add it to the docs.

Description of redir:
 Redirect TCP connections
 It can run under inetd or stand alone (in which case it handles
 multiple connections).  It is 8 bit clean, not limited to line
 mode, is small and light. Supports transparency, FTP redirects, http
 proxying, and bandwidth limiting.
 .
 redir is all you need to redirect traffic across firewalls authenticate
 based on an IP address etc. No need for the firewall toolkit. The
 functionality of inetd/tcpd and "redir" will allow you to do everything
 you need without screwy telnet/ftp etc gateways. (I assume you are running
 IP Masquerading of course.)

**Comment by krtek4** [comment]
`redir` is a dependency of `vagrant-lxc` when using port forwarding : https://github.com/fgrehm/vagrant-lxc

I think it's a bit out of scope to list all dependencies of our dependencies, but if you're willing to submit a PR, I'll merge it ;)

**Comment by krtek4** [comment]
Maybe we could document that "via" a message in the Vagrant file like it has been done for some plugin needed on WIndows or the stack to deep error ?

**Comment by krtek4** [comment]
I added some installation instruction to the README that should cover the `redir` issue.
