### ISSUE TITLE
Add django-cms role

### ISSUE THREAD

**Issue by T4m** [liip/drifter#67]
Would it be a good idea to have the provisioning for django-cms ?

**Comment by jeanmonod** [comment]
@T4m Why did you close your issue? If you can just explain why, could be interesting for the following that will have the same request... Thanks

**Comment by T4m** [comment]
Yes, It's because setup requirements for djangocms are the same as setup requirements for django. So there's nothing more to install. That means, for django or djangocms, you have to uncoment the roles postgres & django.

We can use https://github.com/liip/djangocms-template to create the djangocms project structure.

**Comment by jeanmonod** [comment]
@T4m Thanks :+1:
