### ISSUE TITLE
Document how to run it on windows

### ISSUE THREAD

**Issue by krtek4** [liip/drifter#68]
Seems we need some specific plugin on windows due to the use of NFS.

Installing https://github.com/winnfsd/vagrant-winnfsd seems to make it work.

This should be documented somehow.

Since you are known windows user @ChristianRiesen @Tobion  any input will be really valuable :)

**Comment by ChristianRiesen** [comment]
I can simply confirm that yes, it works with that.

**Comment by krtek4** [comment]
Idea from @chregu , add :

        if Vagrant::Util::Platform.windows? && !Vagrant.has_plugin?("vagrant-winnfsd ")
            puts "Please install vagrant-winnfsd to have NFS Support on Windows!"
            exit 1
        end

somewhere :)

**Comment by krtek4** [comment]
Closing this as this seems now self documenting.
