### ISSUE TITLE
Silex nginx template doesn't take PHP version into account

### ISSUE THREAD

**Issue by mweibel** [liip/drifter#90]
When using PHP 7.0 and the silex template, it will use the wrong PHP FPM version path. 
```
fastcgi_pass   unix:/var/run/php5-fpm.sock;
```

should be in this case:
```
fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
```

Not sure how you do that usually in other cases. Maybe the php-fpm role should define a variable on which path it is and the nginx template reads that?

**Comment by chregu** [comment]
The same way as the symfony template does:

````        
    fastcgi_pass unix:{{ fpm_socket }};
````
