### ISSUE TITLE
Git sync that config from the project

### ISSUE THREAD

**Issue by krtek4** [liip/drifter#97]
The sync made in the `Vagrantfile` for the Git config is launched inside the project directory and thus include all project specific config alongside with remotes and branches information.

**Reproduction Steps:**

1. activate the `git` role
2. set the `sync_git_with_host` parameter to true
3. `vagrant provision`(inside a git repository that has option)
4. `vagrant ssh`
5. `cd /home/vagrant`
6. `git config --list`

**Expected behavior:**

Only "user-wide" configuration from the host are shown

**Observed behavior:**

All project specific configuration is shown

**Drifter version:** 1.0.2
**Vagrant version:** 1.8.4
**OS and version:** Linux, using LXC

* Problem started happening recently, didn't happen in an older version of Drifter: Git sync was introduced in 1.0.0
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens to my colleagues aswell or only me: Yes

**Comment by chregu** [comment]
I assume
`git config --list --global`
should help

**Comment by chregu** [comment]
`--global` helps. but with each provisioning it adds the same config lines over and over again

```
[user]
	name = Christian Stocker
	email = me@chregu.tv
	signingkey = 1575A89B
	name = Christian Stocker
	email = me@chregu.tv
	signingkey = 1575A89B
	name = Christian Stocker
	email = me@chregu.tv
	signingkey = 1575A89B
	name = Christian Stocker
	email = me@chregu.tv
	signingkey = 1575A89B
	name = Christian Stocker
	email = me@chregu.tv
	signingkey = 1575A89B
[push]
	default = matching
	default = matching
	default = matching
	default = matching
	default = matching
[core]
	excludesfile = ~/.gitignore_global
	excludesfile = ~/.gitignore_global
	excludesfile = ~/.gitignore_global
	excludesfile = ~/.gitignore_global
	excludesfile = ~/.gitignore_global
[commit]
	gpgsign = true
	gpgsign = true
	gpgsign = true
	gpgsign = true
	gpgsign = true
```

**Comment by chregu** [comment]
`        git config --file /home/vagrant/.gitconfig-host --replace-all $KEY "$VALUE"``
(replace-all instead of add) seems to solve the problem
